### ISSUE TITLE
Please add documentation

### ISSUE THREAD

**Issue by charkster** [magicjellybeanfpga/MiniStar-Nano#2]
I just bought a ministar nano from Amazon.com and would like a board schematic and programming guide. I have a JLink programmer which can drive JTAG pins. I need to know which board pins connect to the GW1NSR-LV4CQN48 device. There are multiple LDOs on the board and it would be good to know which pins they are associated with.

Also, the board pin pitch is 1.27mm which I could have determined by taking the board length and dividing by 20 pins... but I incorrectly assumed that it was 2.54mm and would fit on a normal breadboard. I ordered pitch adapters so that I can put the board on my breadboard. It would be useful to others to remind them of this, as my two 20 pin adapter boards cost $3.50 each (an additional $7 to the $17 which the board costs).

I will do my best following the regular MiniStar documentation, but the schematic for the Nano would be appreciated.

**Comment by magicjellybeanfpga** [comment]
Hey thanks for reaching out to us and letting us know about the issue. We are reviewing the schematic and getting more information on the programming information. As soon as we have more information, we will be sending it over directly to you.

-MJB team

**Comment by magicjellybeanfpga** [comment]
Thank you for all the great feedback.  I've uploaded the schematic to the `/pcb/*` folder.  You can use any FT232H, CH552 or GWU2X programming board to program the device by connecting the JTAG pins appropriately along with ground and power.

The materials for the MiniStar standard board should also work for the MiniStar Nano at that point and you can utilize the same materials including the programming instructions from there.

**Comment by charkster** [comment]
@magicjellybeanfpga Thank you!
