### ISSUE TITLE
Use of the external Flash chip

### ISSUE THREAD

**Issue by charkster** [magicjellybeanfpga/MiniStar-Nano#3]
I have a question about the external flash chip. If the internal sram and flash of the GW1NSR-LV4CQN48P are empty, will the external flash be used to configure the FPGA or the MCU, or both?
It is very easy for me to program the external Flash and I was wanting to only use it for FPGA configuration. Can I write the bin file from place-n-route step to the external flash starting at address 0x00?
Thanks.

**Comment by magicjellybeanfpga** [comment]
Hello Charkster, 

The boot order of GOWIN LittleBee devices is based on the "Mode" pins of the device.  If the device is configured to boot from external flash it will attempt this first.  If it fails due to no bitstream or corrupt bitstream, it will then attempt to boot from internal flash.

-MJB Team

**Comment by charkster** [comment]
@magicjellybeanfpga Thanks for letting me know about the "Mode" pins. How do I reach the GW1NSR mode pins (I assume there are 3 pins)? Do they connect to board pins? I could not see them in the schematic.

**Comment by magicjellybeanfpga** [comment]
Hello Charkster,

Looking at he schematic the QFN48 pacakge has a MODE1/MODE2 combination pin on pin 10 that is pulled down by R40.  MODE0 is tied to ground internally within the package.  As a result the default MODE is 'b000 (AUTO BOOT).  AUTO BOOT mode boots from internal flash only.  

If you want to boot from external flash you can remove R40.  There is a weak internal pull up on the MODE1/MODE2 pin, so pulling R40 will put the device in 'b110 (DUAL BOOT) mode.  Dual boot mode will attempt external flash boot first followed by embedded flash.

For more information on boot modes refer to UG290 - Programming and Configuration Guide at gowinsemi.com.

-MJB Team

**Comment by charkster** [comment]
@magicjellybeanfpga Thank you for the suggestion. I will try that now.
